name: Technitium DNS Server
version: a933cf5
slug: technitium-dns
description: Self-hosted DNS server with Home Assistant add-on integration.
url: https://github.com/staerk-ha-addons/addon-technitium-dns
ingress: true
ingress_port: 5380
panel_icon: mdi:dns
startup: services
init: false
arch:
- amd64
- aarch64
map:
- type: ssl
- type: addon_config
  read_only: false
options:
  logQueries: true
  forwarders: Cloudflare (DNS-over-HTTPS)
  enableDnsOverTls: true
  enableDnsOverHttps: true
  enableDnsOverHttps3: true
  enableDnsOverQuic: true
  certfile: /ssl/fullchain.pem
  keyfile: /ssl/privkey.key
  manualConfig: false
  manualCertHandling: false
  log_level: info
schema:
  logQueries: bool
  forwarders: list(Cloudflare (DNS-over-UDP)|Cloudflare (DNS-over-TLS)|Cloudflare
    (DNS-over-HTTPS)|Cloudflare (Oblivious DNS-over-HTTPS))
  enableDnsOverTls: bool
  enableDnsOverHttps: bool
  enableDnsOverHttps3: bool
  enableDnsOverQuic: bool
  keyfile: str?
  certfile: str?
  manualConfig: bool
  manualCertHandling: bool
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
ports:
  53/udp: 53
  443/tcp: 443
  443/udp: 443
  853/tcp: 853
  853/udp: 853
  5380/tcp: 5380
  53443/tcp: 53443
image: ghcr.io/staerk-ha-addons/technitium-dns/{arch}
