name: Technitium DNS Server
version: ea5383e
slug: technitium-dns
description: Self-hosted DNS server with Home Assistant add-on integration.
url: https://github.com/staerk-ha-addons/addon-technitium-dns
ingress: true
ingress_port: 5380
panel_icon: mdi:dns
startup: services
init: false
arch:
- amd64
- aarch64
map:
- type: ssl
- type: addon_config
  read_only: false
options:
  forwarders: Cloudflare (DNS-over-HTTPS)
  logQueries: true
  enableDnsOverTls: true
  enableDnsOverHttps: true
  enableDnsOverQuic: true
  certfile: /ssl/fullchain.pem
  keyfile: /ssl/privkey.key
schema:
  forwarders: "list(\n  Cloudflare (DNS-over-UDP)|\n  Cloudflare (DNS-over-UDP IPv6)|\n\
    \  Cloudflare (DNS-over-TCP)|\n  Cloudflare (DNS-over-TCP IPv6)|\n  Cloudflare\
    \ (DNS-over-TLS)|\n  Cloudflare (DNS-over-TLS IPv6)|\n  Cloudflare (DNS-over-HTTPS)|\n\
    \  Cloudflare (DNS-over-HTTPS IPv6)|\n  Cloudflare (Oblivious DNS-over-HTTPS)|\n\
    \  Cloudflare (Oblivious DNS-over-HTTPS IPv6)\n)"
  logQueries: bool
  enableDnsOverTls: bool
  enableDnsOverHttps: bool
  enableDnsOverQuic: bool
  keyfile: str?
  certfile: str?
ports:
  53/udp: 53
  443/tcp: 443
  443/udp: 443
  853/tcp: 853
  853/udp: 853
  5380/tcp: 5380
  53443/tcp: 53443
image: ghcr.io/staerk-ha-addons/technitium-dns/{arch}
