name: Technitium DNS Server
version: 201cb02
slug: technitium-dns
description: Self-hosted DNS server with Home Assistant add-on integration.
url: https://github.com/staerk-ha-addons/addon-technitium-dns
ingress: true
ingress_port: 5380
panel_icon: mdi:dns
startup: services
init: false
arch:
- amd64
- aarch64
map:
- type: ssl
- type: addon_config
  read_only: false
options:
  forwarders: Cloudflare (DNS-over-HTTPS)
schema:
  forwarders: list(Cloudflare (DNS-over-UDP)|Cloudflare (DNS-over-TLS)|Cloudflare
    (DNS-over-HTTPS)|Cloudflare (Oblivious DNS-over-HTTPS))
  logQueries: bool?
  enableDnsOverTls: bool?
  enableDnsOverHttps: bool?
  enableDnsOverHttps3: bool?
  enableDnsOverQuic: bool?
  hostname: str?
  certfile: str?
  keyfile: str?
  manualConfig: bool?
  manualCertHandling: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
ports:
  53/tcp: null
  53/udp: 53
  443/tcp: null
  443/udp: null
  853/tcp: null
  853/udp: null
  5380/tcp: null
  53443/tcp: null
image: ghcr.io/staerk-ha-addons/technitium-dns/{arch}
