name: Technitium DNS Server
version: 4b96109
slug: technitium-dns
description: Self-hosted DNS server with Home Assistant add-on integration.
url: https://github.com/staerk-ha-addons/addon-technitium-dns
ingress: true
ingress_port: 0
panel_icon: mdi:dns
startup: services
init: false
arch:
- amd64
- aarch64
map:
- type: ssl
- type: addon_config
  read_only: false
host_network: true
image: ghcr.io/staerk-ha-addons/technitium-dns/{arch}
