---
name: Technitium DNS Server
version: dev
slug: technitium-dns
description: Self-hosted DNS server with Home Assistant add-on integration.
url: https://github.com/staerk-ha-addons/addon-technitium-dns
ingress: true
ingress_port: 5380
panel_icon: mdi:dns
startup: services
init: false
arch:
  - amd64
  - aarch64
# yamllint disable rule:truthy
map:
  - type: ssl
  - type: addon_config
    read_only: false
# yamllint enable rule:truthy
options:
  generate_ssl_pfx: false
  ssl_pfx_password: "TechnitiumDNS!SSL"
  certfile: "/ssl/fullchain.pem"
  keyfile: "/ssl/privkey.pem"
  pkcs12file: "/config/ssl/technitium.pfx"
schema:
  generate_ssl_pfx: bool
  ssl_pfx_password: password
  certfile: str
  keyfile: str
  pkcs12file: str
ports:
  53/udp: 53
  853/udp: null
  853/tcp: null
  443/udp: null
  443/tcp: null
ports_description:
  53/udp: Standard DNS service (53/udp)
  853/udp: DNS-over-QUIC (853/udp)
  853/tcp: DNS-over-TLS (853/tcp)
  443/udp: DNS-over-HTTPS (443/udp => HTTP/3)
  443/tcp: DNS-over-HTTPS (443/tcp => HTTP/1.1 + HTTP/2)
